# -*- coding: utf-8 -*-
"""Calculadora.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1s3ujhzL-_iNEBDDNs5mQfz3NAqKUP3Jn
"""

# Inicia um laço infinito para que a calculadora continue funcionando
while True:

    try:
        # Pede ao usuário o primeiro número e converte para float
        num1 = float(input("Digite o primeiro número: "))

        # Pede ao usuário o segundo número e converte para float
        num2 = float(input("Digite o segundo número: "))

        # Mostra as opções de operação disponíveis
        print("\nEscolha a operação:")
        print("1 - Soma")
        print("2 - Subtração")
        print("3 - Multiplicação")
        print("4 - Divisão")

        # Recebe a opção escolhida pelo usuário
        operacao = input("Digite o número da operação desejada: ")

        # Verifica se o usuário escolheu soma
        if operacao == "1":
            # Realiza a soma dos dois números
            resultado = num1 + num2
            # Exibe o resultado
            print("Resultado da soma:", resultado)

        # Verifica se o usuário escolheu subtração
        elif operacao == "2":
            # Realiza a subtração dos dois números
            resultado = num1 - num2
            # Exibe o resultado
            print("Resultado da subtração:", resultado)

        # Verifica se o usuário escolheu multiplicação
        elif operacao == "3":
            # Realiza a multiplicação dos dois números
            resultado = num1 * num2
            # Exibe o resultado
            print("Resultado da multiplicação:", resultado)

        # Verifica se o usuário escolheu divisão
        elif operacao == "4":
            # Verifica se o segundo número é diferente de zero
            if num2 == 0:
                # Exibe erro caso tente dividir por zero
                print("Erro: divisão por zero não é permitida.")
                # Volta para o início do laço
                continue
            # Realiza a divisão
            resultado = num1 / num2
            # Exibe o resultado
            print("Resultado da divisão:", resultado)

        # Caso o usuário digite uma opção inválida
        else:
            # Exibe mensagem de erro
            print("Erro: operação inválida. Tente novamente.")
            # Volta para o início do laço
            continue

        # Pergunta se o usuário deseja continuar usando a calculadora
        continuar = input("\nDeseja fazer outra operação? (s/n): ").lower()

        # Se o usuário digitar algo diferente de 's', o programa encerra
        if continuar != "s":
            # Exibe mensagem de encerramento
            print("Calculadora encerrada. Obrigado por usar!")
            # Interrompe o laço infinito
            break

    except ValueError:
        # Captura erro caso o usuário digite algo que não seja número
        print("Erro: você deve digitar apenas números. Tente novamente.")
        # Volta para o início do laço
        continue